#!/bin/bash

# Test script for connectiong to nuc


echo "Hello World!"

for number in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
do
echo "Connectiong to to nuc$number..."
ssh nuc$number ./csc445/A3/nuc-scripts/nuc-run-script
done

exit 0