package packets;

/**
 * Created by Michael on 4/18/2018.
 */
public enum PacketTypes {
    ACCEPTANCE, ERROR, LOGIN, MULTIPLE_VERIFICATION, PROPOSAL, REQUEST, SINGLE_VERIFICATION, TRANSACTION_ACCEPTED,
    TRANSACTION_DENIED, TRANSACTION_PENDING, TRANSACTION_REQUEST, UPDATE_REQUEST, GENERAL, UPDATE_ACCEPTANCE;
}
