package packets;

import java.io.Serializable;

/**
 * Created by Michael on 4/18/2018.
 */
public enum PacketTypes implements Serializable{
    ACCEPTANCE, ERROR, LEARNING, MULTIPLE_VERIFICATION, PROPOSAL, REQUEST, SINGLE_VERIFICATION, SUB_CHAIN,
    TRANSACTION_ACCEPTED, TRANSACTION_DENIED, TRANSACTION_PENDING, TRANSACTION_REQUEST, UPDATE_REQUEST, GENERAL, UPDATE_ACCEPTANCE;
}
