package packets;

/**
 * Created by Michael on 4/18/2018.
 */
public enum PacketTypes {
    ACCEPTACNE, ERROR, LOGIN, LOGIN_ACCEPTED, LOGIN_DENIED, PROPOSAL, REQUEST, TRANSACTION_ACCEPTED, TRANSACTION_DENIED, TRANSACTION_PENDING,
    TRANSACTION_REQUEST, UPDATE_REQUEST, VERIFICATION
}
